[package]
name = "image-filter-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # This tells Rust to build a dynamic library suitable for WASM

[dependencies]
# Required for `wasm_bindgen` which allows Rust and JavaScript to communicate
wasm-bindgen = "0.2.87"